package com.example.dynamodb.entity;

import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor

@Builder
@Component

@DynamoDBTable(tableName = "User")
public class Employee {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String userId;
	
	@DynamoDBAttribute
	private String name;
	
	@DynamoDBAttribute
	private String email;
	
	@DynamoDBIndexHashKey(globalSecondaryIndexName="date-index")
	private String date;
	
	@DynamoDBAttribute
	@DynamoDBRangeKey
	private String role;
	
}